# numpy套件

In [5]:
import numpy as np
a_ndarray=np.array([1,2,3,4,5])
print(a_ndarray*3)

[ 3  6  9 12 15]


In [7]:
print(type(a_ndarray))
print(a_ndarray.ndim)
print(a_ndarray.shape)
print(a_ndarray.dtype)

<class 'numpy.ndarray'>
1
(5,)
int32


In [14]:
z=np.zeros(6)
print(z)
print(np.zeros((2,6)))
print(np.empty((2,6,2)))
print(np.arrange(10))

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[6.23042070e-307 3.56043053e-307]
  [1.60219306e-306 7.56571288e-307]
  [1.89146896e-307 1.37961302e-306]
  [1.05699242e-307 8.01097889e-307]
  [1.78020169e-306 7.56601165e-307]
  [1.02359984e-306 1.11259940e-306]]

 [[1.11261774e-306 1.78019625e-306]
  [1.11261774e-306 1.78019625e-306]
  [1.11261774e-306 1.78019625e-306]
  [1.24610994e-306 1.11261570e-306]
  [1.37961302e-306 1.11260280e-306]
  [8.34451079e-308 3.91792476e-317]]]


AttributeError: module 'numpy' has no attribute 'arrange'

In [16]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [18]:
a=np.array([np.arange(0,5), np.arange(5,10)])
print(a)
print(a[1,:]) #第二列資料
print(a[:,1]) #第二欄資料
print(a[1,1]) #第二列第二欄的資料


[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6
9


In [31]:
groups=["Modern Web" , "DevOps" , "Cloud" , "big Data" , "security","自我挑戰組" ]
iroman=[56,8,19,14,6,71]
groups_array=np.array(groups)
iroman_array=np.array(iroman)
print(groups_array)
print(iroman_array)

['Modern Web' 'DevOps' 'Cloud' 'big Data' 'security' '自我挑戰組']
[56  8 19 14  6 71]


In [32]:
#用人數去篩選組別
print(iroman_array>=10)
print(groups_array[ iroman_array >= 10])
print(groups_array != "自我挑戰組")
print(iroman_array[groups_array!="自我挑戰組"])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


# Ndarray轉置

In [35]:
my_1d_array=np.arange(10)
print(my_1d_array)
my_2d_array=my_1d_array.reshape((2,5))
print(my_2d_array)
print(my_2d_array.T)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
